name: Deploy

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build static files
      run: npm run build
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Commit files
      run: |
        rm -rf *.html *.css *.js *.xml *.txt docs img statics
        git config user.name "pengtikui"
        git config user.email "949828390@qq.com"
        git add .
        git commit -m "Deploy website version based on ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
