name: Deploy

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install --no-package-lock
    - name: Build static files
      run: npm run build
    - name: Commit files
      run: |
        git reset --hard
        git fetch
        git checkout master
        rm -rf *.html *.css *.js *.xml *.txt *.json docs img statics
        git config user.name "pengtikui"
        git config user.email "949828390@qq.com"
        cp -r ./build/* ./
        git add .
        git commit -m "Deploy website version based on ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
